=== dlabaja/MrtkiBlockReloaded/data/item.schema.json
{
  "definitions": {
    "declension": {
      "type": "object",
      "properties": {
        "matches": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "replacements": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["matches", "replacements"]
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "ID skupiny"
    },
    "matchUpperCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané velkými písmeny (Babiš -> BABIŠ)"
    },
    "matchLowerCase": {
      "type": "boolean",
      "description": "True pokud mají být matchovány i matche psané malými písmeny (Babiš -> babiš)"
    },
    "cases": {
      "type": "object",
      "properties": {
        "1": {"$ref": "#/definitions/declension"},
        "2": {"$ref": "#/definitions/declension"},
        "3": {"$ref": "#/definitions/declension"},
        "4": {"$ref": "#/definitions/declension"},
        "5": {"$ref": "#/definitions/declension"},
        "6": {"$ref": "#/definitions/declension"},
        "7": {"$ref": "#/definitions/declension"}
      },
      "required": ["1", "2", "3", "4", "5", "6", "7"]
    },
    "adjectives": {
      "type": "object",
      "properties": {
        "to": {"$ref": "#/definitions/declension"},
        "ta": {"$ref": "#/definitions/declension"},
        "ten": {"$ref": "#/definitions/declension"},
        "ti": {"$ref": "#/definitions/declension"},
        "ty": {"$ref": "#/definitions/declension"},
        "te": {"$ref": "#/definitions/declension"},
        "tu": {"$ref": "#/definitions/declension"},
        "tou": {"$ref": "#/definitions/declension"},
        "tim": {"$ref": "#/definitions/declension"},
        "tech": {"$ref": "#/definitions/declension"},
        "temi": {"$ref": "#/definitions/declension"}
      },
      "required": ["to", "ta", "ten", "ti", "ty", "te", "tu", "tou", "tim", "tech", "temi"]
    }
  },
  "required": ["name", "matchUpperCase", "matchLowerCase", "cases"]
}

=== dlabaja/MrtkiBlockReloaded/data/other-sources/microslop/items/ai.json
{
  "name": "ai",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "AI"
      ],
      "replacements": [
        "GayEye"
      ]
    },
    "2": {
      "matches": [],
      "replacements": []
    },
    "3": {
      "matches": [],
      "replacements": []
    },
    "4": {
      "matches": [],
      "replacements": []
    },
    "5": {
      "matches": [],
      "replacements": []
    },
    "6": {
      "matches": [],
      "replacements": []
    },
    "7": {
      "matches": [],
      "replacements": []
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/stastny.json
{
  "name": "stastny",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Boris Šťastný",
        "Šťastný"
      ],
      "replacements": [
        "Ministr kotrmelců",
        "S ministerstvem Šťastný",
        "Ve výtahu Nešťastný",
        "Bez dotací pro Strážnici Šťastný",
        "Plukovník Schod",
        "Bez záznamníku Nešťastný"
      ]
    },
    "2": {
      "matches": [
        "Borise Šťastného",
        "Šťastného"
      ],
      "replacements": [
        "Ministra kotrmelců",
        "S ministerstvem Šťastného",
        "Ve výtahu Nešťastného",
        "Bez dotací pro Strážnici Šťastného",
        "Plukovníka Schoda",
        "Bez záznamníku Nešťastného"
      ]
    },
    "3": {
      "matches": [
        "Borisi Šťastnému",
        "Šťastnému"
      ],
      "replacements": [
        "Ministrovi kotrmelců",
        "S ministerstvem Šťastnému",
        "Ve výtahu Nešťastnému",
        "Bez dotací pro Strážnici Šťastnému",
        "Plukovníku Schodovi",
        "Bez záznamníku Nešťastnému"
      ]
    },
    "4": {
      "matches": [
        "Borise Šťastného",
        "Šťastného"
      ],
      "replacements": [
        "Ministra kotrmelců",
        "s ministerstvem Šťastného",
        "Ve výtahu neŠťastného",
        "Bez dotací pro Strážnici Šťastného",
        "Plukovníka Schoda",
        "Bez záznamníku Nešťastného"
      ]
    },
    "5": {
      "matches": [
        "Borisi Šťastný",
        "Šťastný"
      ],
      "replacements": [
        "Ministře kotrmelců",
        "s ministerstvem Šťastný",
        "Ve výtahu neŠťastný",
        "Bez dotací pro Strážnici Šťastný",
        "Plukovníku Schode",
        "Bez záznamníku Nešťastný"
      ]
    },
    "6": {
      "matches": [
        "Borisi Šťastném",
        "Šťastném"
      ],
      "replacements": [
        "Ministrovi kotrmelců",
        "s ministerstvem Šťastném",
        "Ve výtahu neŠťastném",
        "Bez dotací pro Strážnici Šťastném",
        "Plukovníku Schodovi",
        "Bez záznamníku Nešťastném"
      ]
    },
    "7": {
      "matches": [
        "Borisem Šťastným",
        "Šťastným"
      ],
      "replacements": [
        "Ministrem kotrmelců",
        "s ministerstvem Šťastným",
        "Ve výtahu neŠťastným",
        "Bez dotací pro Strážnici Šťastným",
        "Plukovníkem Schodem",
        "Bez záznamníku Nešťastným"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/feri.json
{
  "name": "feri",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Feri",
        "Dominik Feri"
      ],
      "replacements": [
        "Úplně nahej",
        "Predátor z Teplic",
        "Ten co neuhne"
      ]
    },
    "2": {
      "matches": [
        "Feriho",
        "Dominika Feriho"
      ],
      "replacements": [
        "Úplně nahýho",
        "Predátora z Teplic",
        "Toho co neuhne"
      ]
    },
    "3": {
      "matches": [
        "Ferihomu",
        "Dominiku Ferihomu"
      ],
      "replacements": [
        "Úplně nahýmu",
        "Predátorovi z Teplic",
        "Tomu co neuhne"
      ]
    },
    "4": {
      "matches": [
        "Feriho",
        "Dominika Feriho"
      ],
      "replacements": [
        "Úplně nahýho",
        "Predátora z Teplic",
        "Toho co neuhne"
      ]
    },
    "5": {
      "matches": [
        "Feri",
        "Dominiku Feri"
      ],
      "replacements": [
        "Úplně nahej",
        "Predátore z Teplic",
        "Ty co neuhneš"
      ]
    },
    "6": {
      "matches": [
        "Ferihom",
        "Dominiku Ferihom"
      ],
      "replacements": [
        "Úplně nahým",
        "Predátorovi z Teplic",
        "Tom co neuhne"
      ]
    },
    "7": {
      "matches": [
        "Ferihom",
        "Dominikem Ferihom"
      ],
      "replacements": [
        "Úplně nahým",
        "Predátorem z Teplic",
        "Tím co neuhne"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/nerudova.json
{
  "name": "nerudova",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Danuše Nerudová",
        "Nerudová"
      ],
      "replacements": [
        "Banuše Nerudná",
        "DanusHE",
        "Královna komunitních poznámek"
      ]
    },
    "2": {
      "matches": [
        "Danuše Nerudové",
        "Nerudové"
      ],
      "replacements": [
        "Banuše Nerudné",
        "DanusHE",
        "Královny komunitních poznámek"
      ]
    },
    "3": {
      "matches": [
        "Danuši Nerudové",
        "Nerudové"
      ],
      "replacements": [
        "Banuši Nerudné",
        "DanusHE",
        "Královně komunitních poznámek"
      ]
    },
    "4": {
      "matches": [
        "Danuši Nerudovou",
        "Nerudovou"
      ],
      "replacements": [
        "Banuši Nerudnou",
        "DanusHE",
        "Královnu komunitních poznámek"
      ]
    },
    "5": {
      "matches": [
        "Danuše Nerudová",
        "Nerudová"
      ],
      "replacements": [
        "Banuše Nerudná",
        "DanusHE",
        "Královno komunitních poznámek"
      ]
    },
    "6": {
      "matches": [
        "Danuši Nerudové",
        "Nerudové"
      ],
      "replacements": [
        "Banuši Nerudné",
        "DanusHE",
        "Královně komunitních poznámek"
      ]
    },
    "7": {
      "matches": [
        "Danuší Nerudovou",
        "Nerudovou"
      ],
      "replacements": [
        "Banuší Nerudnou",
        "DanusHE",
        "Královnou komunitních poznámek"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/topolanek.json
{
  "name": "topolanek",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Topolánek",
        "Mirek Topolánek"
      ],
      "replacements": [
        "Buran po Toskánsku",
        "Dalíkova amnestie",
        "Švédská trojka"
      ]
    },
    "2": {
      "matches": [
        "Topolánka",
        "Mirka Topolánka"
      ],
      "replacements": [
        "Burana po Toskánsku",
        "Dalíkovy amnestie",
        "Švédské trojky"
      ]
    },
    "3": {
      "matches": [
        "Topolánkovi",
        "Mirkovi Topolánkovi"
      ],
      "replacements": [
        "Buranovi po Toskánsku",
        "Dalíkově amnestii",
        "Švédské trojce"
      ]
    },
    "4": {
      "matches": [
        "Topolánka",
        "Mirka Topolánka"
      ],
      "replacements": [
        "Burana po Toskánsku",
        "Dalíkovu amnestii",
        "Švédskou trojku"
      ]
    },
    "5": {
      "matches": [
        "Topolánku",
        "Mirku Topolánku"
      ],
      "replacements": [
        "Burane po Toskánsku",
        "Dalíkova amnestie",
        "Švédská trojko"
      ]
    },
    "6": {
      "matches": [
        "Topolánkovi",
        "Mirkovi Topolánkovi"
      ],
      "replacements": [
        "Buranovi po Toskánsku",
        "Dalíkově amnestii",
        "Švédské trojce"
      ]
    },
    "7": {
      "matches": [
        "Topolánkem",
        "Mirkem Topolánkem"
      ],
      "replacements": [
        "Buranem po Toskánsku",
        "Dalíkovou amnestií",
        "Švédskou trojkou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/politici/cz/ovcacek.json
{
  "name": "ovcacek",
  "matchUpperCase": true,
  "matchLowerCase": false,
  "cases": {
    "1": {
      "matches": [
        "Ovčáček",
        "Jiří Ovčáček"
      ],
      "replacements": [
        "Buzerant s kabelkou",
        "Zaměstnanec hospicu Lány",
        "Twitterový terrorista"
      ]
    },
    "2": {
      "matches": [
        "Ovčáčka",
        "Jiřího Ovčáčka"
      ],
      "replacements": [
        "Buzeranta s kabelkou",
        "Zaměstnance hospicu Lány",
        "Twitterového terroristy"
      ]
    },
    "3": {
      "matches": [
        "Ovčáčkovi",
        "Jiřímu Ovčáčkovi"
      ],
      "replacements": [
        "Buzerantovi s kabelkou",
        "Zaměstnanci hospicu Lány",
        "Twitterovému terroristovi"
      ]
    },
    "4": {
      "matches": [
        "Ovčáčka",
        "Jiřího Ovčáčka"
      ],
      "replacements": [
        "Buzeranta s kabelkou",
        "Zaměstnance hospicu Lány",
        "Twitterového terroristu"
      ]
    },
    "5": {
      "matches": [
        "Ovčáčku",
        "Jiří Ovčáčku"
      ],
      "replacements": [
        "Buzerante s kabelkou",
        "Zaměstnanče hospicu Lány",
        "Twitterový terroristo"
      ]
    },
    "6": {
      "matches": [
        "Ovčáčkovi",
        "Jiřím Ovčáčkovi"
      ],
      "replacements": [
        "Buzerantovi s kabelkou",
        "Zaměstnanci hospicu Lány",
        "Twitterovém terroristovi"
      ]
    },
    "7": {
      "matches": [
        "Ovčáčkem",
        "Jiřím Ovčáčkem"
      ],
      "replacements": [
        "Buzerantem s kabelkou",
        "Zaměstnancem hospicu Lány",
        "Twitterovým terroristou"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/osobnosti/cz/xaver.json
{
  "name": "vesely",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Luboš Xaver Veselý",
        "Luboš Veselý",
        "Xaver",
        "Xaver Veselý",
        "Luboš „Xaver“ Veselý",
        "Luboš \"Xaver\" Veselý"
      ],
      "replacements": [
        "Vypasená svině",
        "Ruský nok",
        "Ředitel gulagu",
        "Strůjce genocidy chlebíčků",
        "Postrach oleje z friťáku",
        "Otesánek z televize",
        "Blop"
      ]
    },
    "2": {
      "matches": [
        "Luboše Xavera Veselého",
        "Luboše Veselého",
        "Xavera",
        "Xavera Veselého",
        "Luboše „Xavera“ Veselého",
        "Luboše \"Xavera\" Veselého"
      ],
      "replacements": [
        "Vypasené svině",
        "Ruského noku",
        "Ředitele gulagu",
        "Strůjce genocidy chlebíčků",
        "Postracha oleje z friťáku",
        "Otesánka z televize",
        "Blopa"
      ]
    },
    "3": {
      "matches": [
        "Luboši Xaveru Veselému",
        "Luboši Veselému",
        "Xaverovi",
        "Xaverovi Veselému",
        "Luboši „Xaveru“ Veselému",
        "Luboši \"Xaveru\" Veselému"
      ],
      "replacements": [
        "Vypasené svini",
        "Ruskému noku",
        "Řediteli gulagu",
        "Strůjci genocidy chlebíčků",
        "Postrachu oleje z friťáku",
        "Otesánkovi z televize",
        "Blopovi"
      ]
    },
    "4": {
      "matches": [
        "Luboše Xavera Veselého",
        "Luboše Veselého",
        "Xavera",
        "Xavera Veselého",
        "Luboše „Xavera“ Veselého",
        "Luboše \"Xavera\" Veselého"
      ],
      "replacements": [
        "Vypasenou svini",
        "Ruského noka",
        "Ředitele gulagu",
        "Strůjce genocidy chlebíčků",
        "Postracha oleje z friťáku",
        "Otesánka z televize",
        "Blopa"
      ]
    },
    "5": {
      "matches": [
        "Luboši Xavere Veselý",
        "Luboši Veselý",
        "Xavore",
        "Xavere Veselý",
        "Luboši „Xavere“ Veselý",
        "Luboši \"Xavere\" Veselý"
      ],
      "replacements": [
        "Vypasená svině",
        "Ruský noku",
        "Řediteli gulagu",
        "Strůjce genocidy chlebíčků",
        "Postrachu oleje z friťáku",
        "Otesánku z televize",
        "Blope"
      ]
    },
    "6": {
      "matches": [
        "Luboši Xaveru Veselém",
        "Luboši Veselém",
        "Xaverovi",
        "Xaveru Veselém",
        "Luboši „Xaveru“ Veselém",
        "Luboši \"Xaveru\" Veselém"
      ],
      "replacements": [
        "Vypasené svini",
        "Ruském noku",
        "Řediteli gulagu",
        "Strůjci genocidy chlebíčků",
        "Postrachu oleje z friťáku",
        "Otesánkovi z televize",
        "Blopovi"
      ]
    },
    "7": {
      "matches": [
        "Lubošem Xaverem Veselým",
        "Lubošem Veselým",
        "Xaverem",
        "Xaverem Veselým",
        "Lubošem „Xaverem“ Veselým",
        "Lubošem \"Xaverem\" Veselým"
      ],
      "replacements": [
        "Vypasenou sviní",
        "Ruským nokem",
        "Ředitelem gulagu",
        "Strůjcem genocidy chlebíčků",
        "Postrachem oleje z friťáku",
        "Otesánkem z televize",
        "Blopem"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Xaverovo"
      ],
      "replacements": [
        "Otesánkovo",
        "Blopovo"
      ]
    },
    "ta": {
      "matches": [
        "Xaverova"
      ],
      "replacements": [
        "Otesánkova",
        "Blopova"
      ]
    },
    "ten": {
      "matches": [
        "Xaverův"
      ],
      "replacements": [
        "Otesánkův",
        "Blopův"
      ]
    },
    "ti": {
      "matches": [
        "Xaverovi"
      ],
      "replacements": [
        "Otesánkovi",
        "Blopovi"
      ]
    },
    "ty": {
      "matches": [
        "Xaverovy"
      ],
      "replacements": [
        "Otesánkovy",
        "Blopovy"
      ]
    },
    "te": {
      "matches": [
        "Xaverově"
      ],
      "replacements": [
        "Otesánkově",
        "Blopově"
      ]
    },
    "tu": {
      "matches": [
        "Xaverovu"
      ],
      "replacements": [
        "Otesánkovu",
        "Blopovu"
      ]
    },
    "tou": {
      "matches": [
        "Xaverovou"
      ],
      "replacements": [
        "Otesánkovou",
        "Blopovou"
      ]
    },
    "tim": {
      "matches": [
        "Xaverovým"
      ],
      "replacements": [
        "Otesánkovým",
        "Blopovým"
      ]
    },
    "tech": {
      "matches": [
        "Xaverových"
      ],
      "replacements": [
        "Otesánkových",
        "Blopových"
      ]
    },
    "temi": {
      "matches": [
        "Xaverovými"
      ],
      "replacements": [
        "Otesánkovými",
        "Blopovými"
      ]
    }
  }
}

=== dlabaja/MrtkiBlockReloaded/data/items/osobnosti/cz/soukup.json
{
  "name": "soukup",
  "matchUpperCase": true,
  "matchLowerCase": true,
  "cases": {
    "1": {
      "matches": [
        "Soukup",
        "Jaromír Soukup"
      ],
      "replacements": [
        "Větroplach",
        "Debatér sám se sebou",
        "Dvouprocentní premiér",
        "Oportunistická svině",
        "Majitel největší čínské investice v ČR",
        "Hvězda ČSFD"
      ]
    },
    "2": {
      "matches": [
        "Soukupa",
        "Jaromíra Soukupa"
      ],
      "replacements": [
        "Větroplacha",
        "Debatéra sama se sebou",
        "Dvouprocentního premiéra",
        "Oportunistické svině",
        "Majitele největší čínské investice v ČR",
        "Hvězdy ČSFD"
      ]
    },
    "3": {
      "matches": [
        "Soukupovi",
        "Jaromíru Soukupovi"
      ],
      "replacements": [
        "Větroplachovi",
        "Debatérovi sám se sebou",
        "Dvouprocentnímu premiérovi",
        "Oportunistické svini",
        "Majiteli největší čínské investice v ČR",
        "Hvězdě ČSFD"
      ]
    },
    "4": {
      "matches": [
        "Soukupa",
        "Jaromíra Soukupa"
      ],
      "replacements": [
        "Větroplacha",
        "Debatéra sama se sebou",
        "Dvouprocentního premiéra",
        "Oportunistickou svini",
        "Majitele největší čínské investice v ČR",
        "Hvězdu ČSFD"
      ]
    },
    "5": {
      "matches": [
        "Soukupe",
        "Jaromíre Soukupe"
      ],
      "replacements": [
        "Větroplachu",
        "Debatére sám se sebou",
        "Dvouprocentní premiére",
        "Oportunistická svině",
        "Majiteli největší čínské investice v ČR",
        "Hvězdo ČSFD"
      ]
    },
    "6": {
      "matches": [
        "Soukupovi",
        "Jaromíru Soukupovi"
      ],
      "replacements": [
        "Větroplachovi",
        "Debatérovi sám se sebou",
        "Dvouprocentním premiérovi",
        "Oportunistické svini",
        "Majiteli největší čínské investice v ČR",
        "Hvězdě ČSFD"
      ]
    },
    "7": {
      "matches": [
        "Soukupem",
        "Jaromírem Soukupem"
      ],
      "replacements": [
        "Větroplachem",
        "Debatérem sám se sebou",
        "Dvouprocentním premiérem",
        "Oportunistickou sviní",
        "Majitelem největší čínské investice v ČR",
        "Hvězdou ČSFD"
      ]
    }
  },
  "adjectives": {
    "to": {
      "matches": [
        "Soukupovo"
      ],
      "replacements": [
        "Větroplachovo",
        "Oportunistovo"
      ]
    },
    "ta": {
      "matches": [
        "Soukupova"
      ],
      "replacements": [
        "Větroplachova",
        "Oportunistova"
      ]
    },
    "ten": {
      "matches": [
        "Soukupův"
      ],
      "replacements": [
        "Větroplachův",
        "Oportunistův"
      ]
    },
    "ti": {
      "matches": [
        "Soukupovi"
      ],
      "replacements": [
        "Větroplachovi",
        "Oportunistovi"
      ]
    },
    "ty": {
      "matches": [
        "Soukupovy"
      ],
      "replacements": [
        "Větroplachovy",
        "Oportunistovy"
      ]
    },
    "te": {
      "matches": [
        "Soukupově"
      ],
      "replacements": [
        "Větroplachově",
        "Oportunistově"
      ]
    },
    "tu": {
      "matches": [
        "Soukupovu"
      ],
      "replacements": [
        "Větroplachovu",
        "Oportunistovu"
      ]
    },
    "tou": {
      "matches": [
        "Soukupovou"
      ],
      "replacements": [
        "Větroplachovou",
        "Oportunistovou"
      ]
    },
    "tim": {
      "matches": [
        "Soukupovým"
      ],
      "replacements": [
        "Větroplachovým",
        "Oportunistovým"
      ]
    },
    "tech": {
      "matches": [
        "Soukupových"
      ],
      "replacements": [
        "Větroplachových",
        "Oportunistových"
      ]
    },
    "temi": {
      "matches": [
        "Soukupovými"
      ],
      "replacements": [
        "Větroplachovými",
        "Oportunistovými"
      ]
    }
  }
}
